use tinkoff_invest_types as tit;

#[derive(Debug, Clone, PartialEq)]
pub enum OperationKind {
    Unspecified,
    Input,
    BondTax,
    OutputSecurities,
    Overnight,
    Tax,
    BondRepaymentFull,
    SellCard,
    DividendTax,
    Output,
    BondRepayment,
    TaxCorrection,
    ServiceFee,
    BenefitTax,
    MarginFee,
    Buy,
    BuyCard,
    InputSecurities,
    SellMargin,
    BrokerFee,
    BuyMargin,
    Dividend,
    Sell,
    Coupon,
    SuccessFee,
    DividendTransfer,
    AccruingVarmargin,
    WritingOffVarmargin,
    DeliveryBuy,
    DeliverySell,
    TrackMfee,
    TrackPfee,
    TaxProgressive,
    BondTaxProgressive,
    DividendTaxProgressive,
    BenefitTaxProgressive,
    TaxCorrectionProgressive,
    TaxRepoProgressive,
    TaxRepo,
    TaxRepoHold,
    TaxRepoRefund,
    TaxRepoHoldProgressive,
    TaxRepoRefundProgressive,
    DivExt,
    TaxCorrectionCoupon,
}

impl From<tit::OperationType> for OperationKind {
    fn from(value: tit::OperationType) -> Self {
        match value {
            tit::OperationType::Unspecified => OperationKind::Unspecified,
            tit::OperationType::Input => OperationKind::Input,
            tit::OperationType::BondTax => OperationKind::BondTax,
            tit::OperationType::OutputSecurities => OperationKind::OutputSecurities,
            tit::OperationType::Overnight => OperationKind::Overnight,
            tit::OperationType::Tax => OperationKind::Tax,
            tit::OperationType::BondRepaymentFull => OperationKind::BondRepaymentFull,
            tit::OperationType::SellCard => OperationKind::SellCard,
            tit::OperationType::DividendTax => OperationKind::DividendTax,
            tit::OperationType::Output => OperationKind::Output,
            tit::OperationType::BondRepayment => OperationKind::BondRepayment,
            tit::OperationType::TaxCorrection => OperationKind::TaxCorrection,
            tit::OperationType::ServiceFee => OperationKind::ServiceFee,
            tit::OperationType::BenefitTax => OperationKind::BenefitTax,
            tit::OperationType::MarginFee => OperationKind::MarginFee,
            tit::OperationType::Buy => OperationKind::Buy,
            tit::OperationType::BuyCard => OperationKind::BuyCard,
            tit::OperationType::InputSecurities => OperationKind::InputSecurities,
            tit::OperationType::SellMargin => OperationKind::SellMargin,
            tit::OperationType::BrokerFee => OperationKind::BrokerFee,
            tit::OperationType::BuyMargin => OperationKind::BuyMargin,
            tit::OperationType::Dividend => OperationKind::Dividend,
            tit::OperationType::Sell => OperationKind::Sell,
            tit::OperationType::Coupon => OperationKind::Coupon,
            tit::OperationType::SuccessFee => OperationKind::SuccessFee,
            tit::OperationType::DividendTransfer => OperationKind::DividendTransfer,
            tit::OperationType::AccruingVarmargin => OperationKind::AccruingVarmargin,
            tit::OperationType::WritingOffVarmargin => OperationKind::WritingOffVarmargin,
            tit::OperationType::DeliveryBuy => OperationKind::DeliveryBuy,
            tit::OperationType::DeliverySell => OperationKind::DeliverySell,
            tit::OperationType::TrackMfee => OperationKind::TrackMfee,
            tit::OperationType::TrackPfee => OperationKind::TrackPfee,
            tit::OperationType::TaxProgressive => OperationKind::TaxProgressive,
            tit::OperationType::BondTaxProgressive => OperationKind::BondTaxProgressive,
            tit::OperationType::DividendTaxProgressive => OperationKind::DividendTaxProgressive,
            tit::OperationType::BenefitTaxProgressive => OperationKind::BenefitTaxProgressive,
            tit::OperationType::TaxCorrectionProgressive => OperationKind::TaxCorrectionProgressive,
            tit::OperationType::TaxRepoProgressive => OperationKind::TaxRepoProgressive,
            tit::OperationType::TaxRepo => OperationKind::TaxRepo,
            tit::OperationType::TaxRepoHold => OperationKind::TaxRepoHold,
            tit::OperationType::TaxRepoRefund => OperationKind::TaxRepoRefund,
            tit::OperationType::TaxRepoHoldProgressive => OperationKind::TaxRepoHoldProgressive,
            tit::OperationType::TaxRepoRefundProgressive => OperationKind::TaxRepoRefundProgressive,
            tit::OperationType::DivExt => OperationKind::DivExt,
            tit::OperationType::TaxCorrectionCoupon => OperationKind::TaxCorrectionCoupon,
        }
    }
}
