use tinkoff_invest_types as tit;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum OperationType {
    Unspecified,
    Input,
    BondTax,
    OutputSecurities,
    Overnight,
    Tax,
    BondRepaymentFull,
    SellCard,
    DividendTax,
    Output,
    BondRepayment,
    TaxCorrection,
    ServiceFee,
    BenefitTax,
    MarginFee,
    Buy,
    BuyCard,
    InputSecurities,
    SellMargin,
    BrokerFee,
    BuyMargin,
    Dividend,
    Sell,
    Coupon,
    SuccessFee,
    DividendTransfer,
    AccruingVarmargin,
    WritingOffVarmargin,
    DeliveryBuy,
    DeliverySell,
    TrackMfee,
    TrackPfee,
    TaxProgressive,
    BondTaxProgressive,
    DividendTaxProgressive,
    BenefitTaxProgressive,
    TaxCorrectionProgressive,
    TaxRepoProgressive,
    TaxRepo,
    TaxRepoHold,
    TaxRepoRefund,
    TaxRepoHoldProgressive,
    TaxRepoRefundProgressive,
    DivExt,
    TaxCorrectionCoupon,
}

impl From<tit::OperationType> for OperationType {
    fn from(value: tit::OperationType) -> Self {
        match value {
            tit::OperationType::Unspecified => OperationType::Unspecified,
            tit::OperationType::Input => OperationType::Input,
            tit::OperationType::BondTax => OperationType::BondTax,
            tit::OperationType::OutputSecurities => OperationType::OutputSecurities,
            tit::OperationType::Overnight => OperationType::Overnight,
            tit::OperationType::Tax => OperationType::Tax,
            tit::OperationType::BondRepaymentFull => OperationType::BondRepaymentFull,
            tit::OperationType::SellCard => OperationType::SellCard,
            tit::OperationType::DividendTax => OperationType::DividendTax,
            tit::OperationType::Output => OperationType::Output,
            tit::OperationType::BondRepayment => OperationType::BondRepayment,
            tit::OperationType::TaxCorrection => OperationType::TaxCorrection,
            tit::OperationType::ServiceFee => OperationType::ServiceFee,
            tit::OperationType::BenefitTax => OperationType::BenefitTax,
            tit::OperationType::MarginFee => OperationType::MarginFee,
            tit::OperationType::Buy => OperationType::Buy,
            tit::OperationType::BuyCard => OperationType::BuyCard,
            tit::OperationType::InputSecurities => OperationType::InputSecurities,
            tit::OperationType::SellMargin => OperationType::SellMargin,
            tit::OperationType::BrokerFee => OperationType::BrokerFee,
            tit::OperationType::BuyMargin => OperationType::BuyMargin,
            tit::OperationType::Dividend => OperationType::Dividend,
            tit::OperationType::Sell => OperationType::Sell,
            tit::OperationType::Coupon => OperationType::Coupon,
            tit::OperationType::SuccessFee => OperationType::SuccessFee,
            tit::OperationType::DividendTransfer => OperationType::DividendTransfer,
            tit::OperationType::AccruingVarmargin => OperationType::AccruingVarmargin,
            tit::OperationType::WritingOffVarmargin => OperationType::WritingOffVarmargin,
            tit::OperationType::DeliveryBuy => OperationType::DeliveryBuy,
            tit::OperationType::DeliverySell => OperationType::DeliverySell,
            tit::OperationType::TrackMfee => OperationType::TrackMfee,
            tit::OperationType::TrackPfee => OperationType::TrackPfee,
            tit::OperationType::TaxProgressive => OperationType::TaxProgressive,
            tit::OperationType::BondTaxProgressive => OperationType::BondTaxProgressive,
            tit::OperationType::DividendTaxProgressive => OperationType::DividendTaxProgressive,
            tit::OperationType::BenefitTaxProgressive => OperationType::BenefitTaxProgressive,
            tit::OperationType::TaxCorrectionProgressive => OperationType::TaxCorrectionProgressive,
            tit::OperationType::TaxRepoProgressive => OperationType::TaxRepoProgressive,
            tit::OperationType::TaxRepo => OperationType::TaxRepo,
            tit::OperationType::TaxRepoHold => OperationType::TaxRepoHold,
            tit::OperationType::TaxRepoRefund => OperationType::TaxRepoRefund,
            tit::OperationType::TaxRepoHoldProgressive => OperationType::TaxRepoHoldProgressive,
            tit::OperationType::TaxRepoRefundProgressive => OperationType::TaxRepoRefundProgressive,
            tit::OperationType::DivExt => OperationType::DivExt,
            tit::OperationType::TaxCorrectionCoupon => OperationType::TaxCorrectionCoupon,
        }
    }
}
