name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build protobuf library
      run: |
        git clone https://github.com/protocolbuffers/protobuf.git
        cd protobuf
        git submodule update --init --recursive
        bazel build :protoc :protobuf
        cp bazel-bin/protoc /usr/local/bin
        cp src/google/protobuf/timestamp.proto /usr/local/include
    - name: Build
      run: cargo build --verbose
